version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo

  min-java-image:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: db-prod
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_AUT_DB: admin
    depends_on:
      - mongo