version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - /data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo
    ports:
      - 8081:8081

  java-image:
    build: .
    ports:
      - 8085:8080
    depends_on:
      - mongo-express